<?xml version="1.0"?>
<sdf version="1.7" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="pendulum" params="name mass length radius color *pose *dynamics">
    <model name="${name}">
      <xacro:insert_block name="pose"/>
      <frame name="base_link">
      <pose>0 0 0 0 0 0</pose>
      </frame>
      <joint name="joint" type="revolute">
        <parent>world</parent>
        <child>rod</child>
        <pose relative_to="base_link">0 0 0 0 0 0</pose>
        <axis>
          <xyz>1 0 0</xyz>
          <xacro:insert_block name="dynamics" />
          <limit>
            <lower>-1e+16</lower>
            <upper>1e+16</upper>
          </limit>
        </axis>
      </joint>
      <link name="rod">
        <pose relative_to="base_link">0 0 ${-length/2} 0 0 0</pose>
        <inertial>
          <pose>0 0 ${-length/2} 0 0 0</pose>
          <mass>${mass}</mass>
          <inertia>
            <ixx>${1/3 * mass * length * length}</ixx>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyy>${1/3 * mass * length * length}</iyy>
            <iyz>0</iyz>
            <izz>${1/3 * mass * length * length}</izz>
          </inertia>
        </inertial>
        <collision name="rod_collision">
          <pose>0 0 0 0 0 0</pose>
          <geometry>
            <cylinder>
              <length>${length}</length>
              <radius>${radius}</radius>
            </cylinder>
          </geometry>
          <surface>
            <contact>
              <ode>
                <kp>1e+06</kp>
                <kd>1</kd>
              </ode>
            </contact>
            <friction>
              <ode>
                <mu>1</mu>
                <mu2>1</mu2>
              </ode>
            </friction>
          </surface>
        </collision>
        <visual name="rod_visual">
          <pose>0 0 0 0 0 0</pose>
          <geometry>
            <cylinder>
              <length>${length}</length>
              <radius>${radius}</radius>
            </cylinder>
          </geometry>
          <material>
            <ambient>${color}</ambient>
            <diffuse>${color}</diffuse>
            <specular> 0.01 0.01 0.01 1.000000 1.500000</specular>
          </material>
        </visual>
        <gravity>1</gravity>
        <velocity_decay/>
      </link>
    </model>
  </xacro:macro>

  <xacro:macro name="static_plane" params="name length width *pose">
    <model name="${name}">
      <xacro:insert_block name="pose" />
      <static>1</static>
      <link name="${name}_link">
        <pose>0 0 0 0 0 0</pose>
        <collision name="${name}_collision">
          <pose relative_to="${name}_link">0 0 0 0 0 0</pose>
          <geometry>
            <box>
              <size>${length} ${width} 0.02</size>
            </box>
          </geometry>
          <surface>
            <contact>
              <ode>
                <kp>1e+06</kp>
                <kd>1</kd>
              </ode>
            </contact>
            <friction>
              <ode>
                <mu>1</mu>
                <mu2>1</mu2>
              </ode>
            </friction>
          </surface>
        </collision>
        <visual name="${name}_visual">
          <pose>0 0 0 0 0 0</pose>
          <geometry>
            <box>
              <size>${length} ${width} 0.02</size>
            </box>
          </geometry>
          <material>
            <ambient> .3 .3 .3  1.0</ambient>
            <diffuse> .7 .7 .7  1.0</diffuse>
            <specular> 0.01 0.01 0.01 1.000000 1.500000</specular>
          </material>
        </visual>
        <gravity>0</gravity>
        <velocity_decay/>
      </link>
    </model>
  </xacro:macro>

  <!-- A ground plane -->
  <xacro:macro name="ground_plane">
    <xacro:property name="length" value="100"/>
    <xacro:property name="width" value="100"/>
    <model name='ground_plane'>
      <static>1</static>
      <pose>0 0 0 0 0 0</pose>
      <link name='link'>
        <collision name='collision'>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>${length} ${width}</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode/>
            </friction>
            <contact/>
          </surface>
        </collision>
        <visual name='visual'>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>${length} ${width}</size>
            </plane>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>
  </xacro:macro>


  <!-- A global light source -->
  <xacro:macro name="sun">
    <light name='sun' type='directional'>
      <cast_shadows>1</cast_shadows>
      <pose>0 0 10 0 -0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
      <spot>
        <inner_angle>0</inner_angle>
        <outer_angle>0</outer_angle>
        <falloff>0</falloff>
      </spot>
    </light>
  </xacro:macro>

</sdf>