name: publish_docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [publish-docs]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup config
        uses: athackst/athackst.mkdocs@main
      - name: Build and push docs to gh-pages
        uses: athackst/mkdocs-simple-plugin@main
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: site
          ignore_urls: |
            https://fonts.gstatic.com
            /http://sdformat.org/
            /https://gazebosim.org/
